KNOWN_ELEMENTS = [
  'a', 'abbr', 'abbrs', 'address', 'addresses', 'area', 
  'areas', 'article', 'articles', 'as', 'aside', 'asides', 
  'audio', 'audios', 'b', 'base', 'bases', 'bdi', 'bdis', 
  'bdo', 'bdos', 'blockquote', 'blockquotes', 'body', 'bodys', 
  'br', 'brs', 'bs', 'button', 'buttons', 'canvas', 'canvases', 
  'caption', 'captions', 'checkbox', 'checkboxes', 'cite', 
  'cites', 'code', 'codes', 'col', 'colgroup', 'colgroups', 
  'cols', 'command', 'commands', 'datalist', 'datalists', 
  'dd', 'dds', 'del', 'dels', 'details', 'dfn', 'dfns', 'div', 
  'divs', 'dl', 'dls', 'dt', 'dts', 'element', 'elements', 
  'em', 'embed', 'embeds', 'ems', 'fieldset', 'fieldsets', 'figcaption', 
  'figcaptions', 'figure', 'figures', 'file_field', 'file_fields', 'font', 
  'fonts', 'footer', 'footers', 'form', 'forms', 'frame', 'frames', 
  'h1', 'h1s', 'h2', 'h2s', 'h3', 'h3s', 'h4', 'h4s', 'h5', 'h5s', 'h6', 
  'h6s', 'head', 'header', 'headers', 'heads', 'hgroup', 'hgroups', 
  'hidden', 'hiddens', 'hr', 'hrs', 'html', 'htmls', 'i', 'iframe', 
  'iframes', 'img', 'imgs', 'input', 'inputs', 'ins', 'inses', 
  'is', 'kbd', 'kbds', 'keygen', 'keygens', 'label', 'labels', 'legend', 
  'legends', 'li', 'link', 'lis', 'map', 'maps', 'mark', 'marks', 'menu', 'menus', 
  'meta', 'metas', 'meter', 'meters', 'nav', 'navs', 'noscript', 'noscripts', 
  'object', 'objects', 'ol', 'ols', 'optgroup', 'optgroups', 'option', 'options', 
  'output', 'outputs', 'p', 'param', 'params', 'pre', 'pres', 'progress', 'progresses', 
  'ps', 'q', 'qs', 'radio', 'radios', 'rp', 'rps', 'rt', 'rts', 'rubies', 'ruby', 's', 
  'samp', 'samps', 'script', 'scripts', 'section', 'sections', 'select', 'selects', 'small', 
  'smalls', 'source', 'sources', 'span', 'spans', 'ss', 'strong', 'strongs', 'style', 'styles', 
  'sub', 'subs', 'summaries', 'summary', 'sup', 'sups', 'table', 'tables', 'tbody', 'tbodys', 'td', 
  'tds', 'text_field', 'text_fields', 'textarea', 'textareas', 'tfoot', 'tfoots', 'th', 'thead', 
  'theads', 'ths', 'time', 'times', 'title', 'titles', 'tr', 'track', 'tracks', 'trs', 'ul', 
  'uls', 'var', 'vars', 'video', 'videos', 'wbr', 'wbrs'
]
